apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: eval
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3307  
      targetPort: 3306  
